package asciiart

import (
	"bytes"
	"fmt"
	"io"
)

// BashOptions controls bash-script rendering.
type BashOptions struct {
	// Fragment emits just a "cat <<'EOF' ... EOF" snippet instead of a
	// full, directly-runnable script, for pasting into an existing script.
	Fragment bool
	// FuncName is the shell function the art is wrapped in. Defaults to
	// "show_ascii_art".
	FuncName string
	// Title is used in the header comment (e.g. the source image path).
	Title string
}

const bashHeredocDelim = "ASCII_ART_EOF"

// RenderBash writes the grid as a standalone bash script: the ANSI art is
// embedded in a quoted heredoc (so escape codes and any special
// characters pass through literally, unexpanded) inside a function.
// Running the script directly prints the art immediately; sourcing it
// (`source art.sh`) just defines the function for the caller to invoke
// whenever it wants, e.g. as a banner in another script.
func RenderBash(w io.Writer, g *Grid, colorMode AnsiColorMode, opts BashOptions) error {
	if opts.FuncName == "" {
		opts.FuncName = "show_ascii_art"
	}

	var body bytes.Buffer
	if err := RenderANSI(&body, g, colorMode); err != nil {
		return err
	}

	if opts.Fragment {
		_, err := fmt.Fprintf(w, "cat <<'%s'\n%s%s\n", bashHeredocDelim, body.String(), bashHeredocDelim)
		return err
	}

	title := opts.Title
	if title == "" {
		title = "an image"
	}

	_, err := fmt.Fprintf(w, `#!/usr/bin/env bash
# ASCII art generated by ascii-converter from %s.
# Run directly to print it, or source this file to make %s
# available to call from another script.

%s() {
  cat <<'%s'
%s%s
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  %s
fi
`, title, opts.FuncName, opts.FuncName, bashHeredocDelim, body.String(), bashHeredocDelim, opts.FuncName)
	return err
}
